{% set name = "pathspec" %}
{% set version = "0.10.3" %}
{% set checksum = "56200de4077d9d0791465aa9095a01d421861e405b5096955051deefd697d6f6" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
  run:
    - python

test:
  source_files:
    - tests/
  requires:
    - pytest
  imports:
    - pathspec
  commands:
    - pip check
    - cd tests && pytest --verbose  # [unix]
    # skip symlink tests on windows
    # https://github.com/cpburnz/python-path-specification/commit/d268375a4c6aa
    ## tests seem to have issues running on win-64 in our CI system
    ## as a workaround, try uploading to a staging channel and run the test suite from a dev instance before finalizing the build
    - cd tests && pytest --verbose  # [win]

about:
  home: https://github.com/cpburnz/python-path-specification
  license: MPL-2.0
  license_file: LICENSE
  license_family: Other
  summary: 'Utility library for gitignore style pattern matching of file paths.'

  description: |
    pathspec is a utility library for pattern matching of file paths. So far
    this only includes Git's wildmatch pattern matching which itself is derived
    from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
  doc_url: https://python-path-specification.readthedocs.io
  doc_source_url: https://github.com/cpburnz/python-path-specification/blob/master/doc/source/index.rst
  dev_url: https://github.com/cpburnz/python-path-specification

extra:
  recipe-maintainers:
    - bollwyvl
    - proinsias
