{% set name = "pathspec" %}
{% set version = "1.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17db5ecd524104a120e173814c90367a96a98d07c45b2e10c2f3919fff91bf5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<5
  run:
    - python
  run_constrained:
    # hyperscan
    - hyperscan >=0.7
    # optional
    - typing-extensions >=4
    # re2
    - google-re2 >=1.1

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=8
  imports:
    - pathspec
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/cpburnz/python-path-specification
  license: MPL-2.0
  license_file: LICENSE
  license_family: Other
  summary: Utility library for gitignore style pattern matching of file paths.
  description: |
    pathspec is a utility library for pattern matching of file paths. So far
    this only includes Git's wildmatch pattern matching which itself is derived
    from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
  doc_url: https://python-path-specification.readthedocs.io
  dev_url: https://github.com/cpburnz/python-path-specification

extra:
  recipe-maintainers:
    - bollwyvl
    - proinsias
