{% set name = "pathspec" %}
{% set version = "0.12.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a482d51503a1ab33b1c67a6c3813a26953dbdc71c31dacaef9a838c4e29f5712

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
    - setuptools >=40.8.0
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - pathspec
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/cpburnz/python-path-specification
  license: MPL-2.0
  license_file: LICENSE
  license_family: Other
  summary: Utility library for gitignore style pattern matching of file paths.
  description: |
    pathspec is a utility library for pattern matching of file paths. So far
    this only includes Git's wildmatch pattern matching which itself is derived
    from Rsync's wildmatch. Git uses wildmatch for its gitignore files.
  doc_url: https://python-path-specification.readthedocs.io
  dev_url: https://github.com/cpburnz/python-path-specification

extra:
  recipe-maintainers:
    - bollwyvl
    - proinsias
